version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "daily"
